### ISSUE TITLE
SSIM tuning does not work in "tr_TR" locale

### ISSUE THREAD

**Issue by nulledone** [stax76/staxrip#230] opened 2017-07-21 13:32 UTC
Here goes the log (file directory was irrelevant so changed with *)

> Error Encoding video using x265 2.4+96 x64
> 
> Encoding video using x265 2.4+96 x64 failed with exit code: 1 (0x1)
> 
> The exit code might be a system error code: STATUS_WAIT_1
> 
> The exit code might be a system error code: Incorrect function.
> 
> 
> -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
>             Encoding video using x265 2.4+96 x64
> -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
> 
> cmd.exe /S /C ""D:\Program Files\Staxrip\Apps\avs2pipemod\avs2pipemod64.exe" -y4mp "*.avs" | "D:\Program Files\Staxrip\Apps\x265\x265.exe" --crf 20 --preset veryfast --tune ssım --profile main10 --output-depth 10 --frames 2111 --y4m --output "*.hevc" -"
> 
> x265 [error]: preset or tune unrecognized
> avs2pipemod[info]: writing 2111 frames of 30/1 fps, 1280x720,
>                    sar 0:0, YUV-420-planar-8bit progressive video.
> avs2pipemod[info]: finished, wrote 0 frames [0%].
> avs2pipemod[info]: total elapsed time is 0.006 sec.
> avs2pipemod[error]: only wrote 0 of 2111 frames.
> 
> 
> 
> StaxRip.ErrorAbortException: Encoding video using x265 2.4+96 x64 failed with exit code: 1 (0x1)
> 
> The exit code might be a system error code: STATUS_WAIT_1
> 
> The exit code might be a system error code: Incorrect function.
> Version: StaxRip x64 1.5.1.9 unstable test build

As you see, as a tuning it uses ss*ı*m (dotless i) instead of SSIM or ssim. To reproduce this problem no need for a fully Turkish windows ISO, changing locale&keyboard to "Turkish (Turkey)" seems enough.

**Comment by stax76** [comment] 2017-07-21 13:40
Hi, which operating system?

**Comment by nulledone** [comment] 2017-07-21 13:48
Windows 8.1 also occurs on latest unstable 1.5.3.3 (you are working hard, not even 2 weeks since 1.5.1.9)

**Comment by stax76** [comment] 2017-07-21 14:03
I often upload a build with only a fix only hours after a bug report. Internationalization and backward compatibility from 7-10 have highest priority for me so I will do be best to find a solution, could take a day or two, I'm going out now. :-)

**Comment by nulledone** [comment] 2017-07-21 14:12
Oh alright, anyway if you've meant translations by "Internationalization" I am up to translate this awesome thing to Turkish.

**Comment by stax76** [comment] 2017-07-21 21:10
Thanks for the translation offer, it was translated ten years ago but was dropped because it's a huge task, the menus can be customized and are part of the settings, there are about 40 dialogs so it's a rather big app. A translation system has to be build from ground up.

On my test system changing the region alone is not enough to reproduce it, I'll try now to change the keyboard too.

```
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Users\Frank> [System.Text.Encoding]::Default

IsSingleByte      : True
BodyName          : iso-8859-9
EncodingName      : Türkisch (Windows)
HeaderName        : windows-1254
WebName           : windows-1254
WindowsCodePage   : 1254
IsBrowserDisplay  : True
IsBrowserSave     : True
IsMailNewsDisplay : True
IsMailNewsSave    : True
EncoderFallback   : System.Text.InternalEncoderBestFitFallback
DecoderFallback   : System.Text.InternalDecoderBestFitFallback
IsReadOnly        : True
CodePage          : 1254

PS C:\Users\Frank> chcp
Aktive Codepage: 857.
PS C:\Users\Frank>

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                     System Environment
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

StaxRip    : 1.5.3.4
Windows    : Windows 7 Home Premium
Language   : German (Germany)
CPU        : Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
GPU        : VMware SVGA 3D
Resolution : 3840 x 1991
DPI        : 96

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
            Encoding video using x265 2.5+2 x64
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

cmd.exe /S /C "C:\Users\Frank\Desktop\bin\Apps\avs2pipemod\avs2pipemod64.exe
 -y4mp C:\Users\Frank\Desktop\Samples\aaa_temp\aaa.avs | 
C:\Users\Frank\Desktop\bin\Apps\x265\x265.exe --crf 20 --preset ultrafast
--tune ssim --profile main10 --output-depth 10 --sar 44:45 --frames 1301
--y4m --output C:\Users\Frank\Desktop\Samples\aaa_temp\aaa_out.hevc -"

y4m  [info]: 640x352 fps 30000/1001 i420p8 sar 44:45 unknown frame count
raw  [info]: output file: C:\Users\Frank\Desktop\Samples\aaa_temp\aaa_out.hevc
x265 [info]: HEVC encoder version 2.5+2-18fa144d453e
x265 [info]: build info [Windows][GCC 7.1.0][64 bit] 10bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
x265 [info]: Main 10 profile, Level-2.1 (Main tier)
x265 [info]: Thread pool created using 1 threads
x265 [info]: Slices                              : 1
x265 [info]: frame threads / pool features       : 1 / wpp(11 rows)
x265 [warning]: Source height < 720p; disabling lookahead-slices
x265 [info]: Coding QT: max CU size, min CU size : 32 / 16
x265 [info]: Residual QT: max TU size, max depth : 32 / 1 inter / 1 intra
x265 [info]: ME / range / subpel / merge         : dia / 57 / 0 / 2
x265 [info]: Keyframe min / max / scenecut / bias: 25 / 250 / 0 / 5.00
x265 [info]: Lookahead / bframes / badapt        : 5 / 3 / 0
x265 [info]: b-pyramid / weightp / weightb       : 1 / 0 / 0
x265 [info]: References / ref-limit  cu / depth  : 1 / off / off
x265 [info]: AQ: mode / str / qg-size / cu-tree  : 2 / 0.0 / 32 / 1
x265 [info]: Rate Control / qCompress            : CRF-20.0 / 0.60
x265 [info]: tools: rd=2 early-skip rskip tmvp fast-intra
x265 [info]: tools: strong-intra-smoothing deblock
avs2pipemod[info]: writing 1301 frames of 30000/1001 fps, 640x352,
sar 0:0, YUV-420-planar-8bit progressive video.
avs2pipemod[info]: finished, wrote 1301 frames [100%].
avs2pipemod[info]: total elapsed time is 16.609 sec.
x265 [info]: frame I:      6, Avg QP:22.73  kb/s: 2775.10
x265 [info]: frame P:    326, Avg QP:24.79  kb/s: 1107.25
x265 [info]: frame B:    969, Avg QP:27.67  kb/s: 202.52
x265 [info]: consecutive B-frames: 1.2% 1.5% 1.5% 95.8%
encoded 1301 frames in 21.77s (59.77 fps), 441.09 kb/s, Avg QP:26.92

Start:    23:02:03
End:      23:02:25
Duration: 00:00:21

General
Complete name        : C:\Users\Frank\Desktop\Samples\aaa_temp\aaa_out.hevc
Format               : HEVC
Format/Info          : High Efficiency Video Coding
File size            : 2.29 MiB
Writing library      : x265 2.5+2-18fa144d453e:[Windows][GCC 7.1.0][64 bit] 10bit

Video
Format               : HEVC
Format/Info          : High Efficiency Video Coding
Format profile       : Main 10@L2.1@Main
Width                : 640 pixels
Height               : 352 pixels
Display aspect ratio : 16:9
Frame rate           : 29.970 (30000/1001) FPS
Color space          : YUV
Chroma subsampling   : 4:2:0
Bit depth            : 10 bits
Writing library      : x265 2.5+2-18fa144d453e:[Windows][GCC 7.1.0][64 bit] 10bit
```

**Comment by stax76** [comment] 2017-07-21 21:17
Why would you want to merge? By default mpeg2 is merged with DGIndex and the rest with mkvmerge, if that works well depends on the format, best solution it not to split to begin with.

**Comment by stax76** [comment] 2017-07-21 21:30
Ok, I changed more region settings and can now reproduce it.

**Comment by stax76** [comment] 2017-07-21 22:36
It's fixed in the build below, I wrote a explanation in the changelog what was wrong exactly.

https://github.com/stax76/staxrip/blob/master/md/changelog.md

**Closed by stax76** 2017-07-21 22:36 UTC
