### ISSUE TITLE
StaxRip TestBuild 2016-04-26 audio demuxing not working

### ISSUE THREAD

**Issue by northwest1976** [stax76/StaxRip#62] opened 2016-04-23 18:34 UTC

**Comment by stax76** [comment] 2016-04-23 20:48
Is the new demuxing option enabled?

**Comment by northwest1976** [comment] 2016-04-24 11:02
Yes

**Comment by stax76** [comment] 2016-04-24 12:34
> To solve problems I have to see a full log file uploaded to www.pastebin.com. pastebin has a auto expire feature which must be set to 30 days.

https://stax76.gitbooks.io/staxrip-handbook/content/

**Comment by northwest1976** [comment] 2016-04-26 12:08
![1](https://cloud.githubusercontent.com/assets/18382344/14817440/a7bfa0d4-0bb7-11e6-86c7-e95055fc4862.PNG)
![2](https://cloud.githubusercontent.com/assets/18382344/14817449/ad455044-0bb7-11e6-8901-6d82ff597500.PNG)
![3](https://cloud.githubusercontent.com/assets/18382344/14817456/b4abff36-0bb7-11e6-9587-bedcfe3f204e.PNG)
![4](https://cloud.githubusercontent.com/assets/18382344/14817461/b8ddf960-0bb7-11e6-8fce-d85cdd6f2e49.PNG)

http://pastebin.com/1gKEsAQW

**Comment by stax76** [comment] 2016-04-26 14:29
Thanks for the info, unfortunately I still cannot reproduce it.

What was your source filter before you opened the source? Manual (default), Automatic, or DGSource?

Did you change anything at Tools > Settings > Demuxing

What happens if you do:

Tools > Settings > Demuxing > Restore

OT: is there a particular reason to use 2 pass, I generally don't recommend it.

**Comment by northwest1976** [comment] 2016-04-26 17:34
Thanks Frank,
the problem is solved, new test-build 2016-04-26 18-31 work fine

**Comment by stax76** [comment] 2016-04-26 17:46
alright fine

**Comment by northwest1976** [comment] 2016-04-27 09:52
It's an error
yyou can reproduce error when second audio track No Audio is

![1](https://cloud.githubusercontent.com/assets/18382344/14848473/2df06de4-0c6e-11e6-9435-e710f96b0718.PNG)

**Comment by stax76** [comment] 2016-04-27 10:33
It's fixed now: https://github.com/stax76/staxrip#download

**Closed** 2016-04-27 10:33 UTC
