### ISSUE TITLE
[Feature] Add subtitle options to template

### ISSUE THREAD

**Issue by Zcehtro** [stax76/staxrip#161] opened 2017-05-09 16:54 UTC
StaxRip lacks automating for subtitles.

It would be extremely useful to add subtitles settings and configurations to the template (if and when subtitles are found). If there are no subtitles then the template doesn't add any extra settings since there are no subtitles to apply the settings to.

For example:

![image](https://cloud.githubusercontent.com/assets/10564090/25862229/f5508c2c-34ac-11e7-925a-f3ef9db68502.png)
If the video has a subtitle track, then I would like to automatically (by using the template) always set the name of the subtitle track to English (or to name the track as the language of the subtitle, etc.). I usually do this by clicking the Set Name button, but it is tedious because I process many and there is no way to automate this.
Also, if there is only ONE subtitle found, it would be extremely useful to automate it being set to Default, that way it is enabled by default when the video is played.

There could be an option to automate the options for several subtitle tracks IF FOUND. ie Set the first or second to Default, etc.

And if there are no subtitles found in the source file when processing a directory or folder, then the subtitle options don't apply and nothing is changed.

It would be a great feature to automate settings for tracks "when found" that don;t just apply to subtitle tracks, but audio tracks as well. But to keep it simple, this feature subject is for the subtitles. :)

**Comment by stax76** [comment] 2017-05-10 20:06
Please try the build from today, it has two new options.

**Comment by Zcehtro** [comment] 2017-05-11 00:28
Sweet. I'll check it out and write back.

**Comment by Zcehtro** [comment] 2017-05-11 04:12
Awesome. Found the differences here:

![image](https://cloud.githubusercontent.com/assets/10564090/25932063/87c17494-35d5-11e7-8677-e42a1bfc2f81.png)

However, the subtitles options weren't applied correctly according to the options I used (in the screenshot).

![image](https://cloud.githubusercontent.com/assets/10564090/25932131/be474336-35d5-11e7-916c-73224491a16d.png)

The subtitle name remained as a variable and wasn't expanded, and I guess that is why the Default subtitle option didn't apply either.

**Comment by Zcehtro** [comment] 2017-05-11 04:16
I tried it again, and this time I used no variables:

![image](https://cloud.githubusercontent.com/assets/10564090/25932231/8e597bb6-35d6-11e7-9036-f802ca577ff8.png)

This applied the name correctly, but the Default subtitle checkbox is still unchecked:

![image](https://cloud.githubusercontent.com/assets/10564090/25932245/a49ecb7e-35d6-11e7-8a6d-6b65fecae0de.png)

**Comment by stax76** [comment] 2017-05-11 07:46
It's by design, the expansion happens at muxing stage, and the default enabling happens at automatic subtitle discovery, it don't happen when you manually add subtitles in the dialog.

**Comment by Zcehtro** [comment] 2017-05-11 13:18
I didn't add anything manually. 
They were found by the program.

I used Source -> Single File.

**Comment by stax76** [comment] 2017-05-11 13:34
You have to set up the options before you open the source file.

**Comment by Zcehtro** [comment] 2017-05-11 14:02
This is what I did (using the settings from the screenshots and getting the same results):

https://www.dropbox.com/s/6fno394em2gi0hp/FFsplit-170511-085229.mp4?dl=0

**Comment by stax76** [comment] 2017-05-11 14:57
It wasn't my best day when I coded this, sorry. I'll upload a fixed build soon.

**Comment by Zcehtro** [comment] 2017-05-11 14:58
It's cool. Just helping out.

**Comment by stax76** [comment] 2017-05-11 20:31
It's online now.

**Comment by Zcehtro** [comment] 2017-05-12 00:51
Ok. I'll post back when I tried it.

**Comment by Zcehtro** [comment] 2017-05-12 05:38
Ok. Just finished looking at it as thoroughly as possible. It's all working now. :)

JIC I wanted to point this out:
Leaving the subtitle variable unexpanded prevents me from knowing what value it holds.
I'm referring to Language Native (%language_native%) and Language English (%language_english%).
Perhaps a popup balloon or something else could briefly show the values of the variables so the user can know what he's working with.

Here are the combinations I tested:

![image](https://cloud.githubusercontent.com/assets/10564090/25983526/f171f910-36aa-11e7-9043-7e0149a2c4f6.png)

**Comment by Zcehtro** [comment] 2017-05-12 05:46
One last thing.... I found an odd glitch in the subtitles when re-encoding a video file.

The source file shows this:

![image](https://cloud.githubusercontent.com/assets/10564090/25983727/2dfd6d28-36ac-11e7-9c82-b704d9c23d8b.png)

And the new file shows this:

![image](https://cloud.githubusercontent.com/assets/10564090/25983746/3bb263ce-36ac-11e7-921d-ba76906c2343.png)

There is an Edition segment that wasn't there before, and I don't know where it came from. I haven't added any options to the subtitles besides the ones in the previous screenshots.

Let me know what file you need from my side to debug this.

**Comment by stax76** [comment] 2017-05-12 11:37
I don't know about editions, take a look at the source with the built in MediaInfo GUI found in the context menu, it has a search feature you can use to search for 'edition' and '45'.

**Comment by Zcehtro** [comment] 2017-05-12 16:08
Just did it and found no reason why it would do that. The MediaInfo shows the presence of a new menu after the chapters, but no explanation as to why it occurred.

These are the MediaInfo datas:

[mediainfo_old video.txt](https://github.com/stax76/staxrip/files/997319/mediainfo_old.video.txt)
[mediainfo_new video.txt](https://github.com/stax76/staxrip/files/997320/mediainfo_new.video.txt)

Here's the difference generated between the MediaInfo from the new and old videos:

https://www.diffchecker.com/e0Iut7HP

**Comment by stax76** [comment] 2017-05-12 16:14
According for 'mkvmerge editions' showed it relates probably to chapters, please post the full log.

**Comment by Zcehtro** [comment] 2017-05-12 16:17
Can you explain how do I produce the log? Because every log for every video I processed disappears, it isn't stored.

**Comment by stax76** [comment] 2017-05-12 16:19
After the job finished you can find it at Tools > Loog File in the main menu. It's located in the temp dir *_staxrip.log

**Comment by Zcehtro** [comment] 2017-05-12 16:22
I get this every time:

![image](https://cloud.githubusercontent.com/assets/10564090/26007226/2f8d72e2-3705-11e7-837c-8d3e03a0ad7a.png)

It's never stored.

**Comment by stax76** [comment] 2017-05-12 16:27
You need to load a source file first.

**Comment by Zcehtro** [comment] 2017-05-12 16:50
Is there a way for the log to be preserved after the video is done processing?

**Comment by stax76** [comment] 2017-05-12 16:53
It's always preserved unless you use Options > Misc > Delete temp files directory

**Comment by Zcehtro** [comment] 2017-05-12 19:36
Here it is. Hope it helps.

[Star.Trek.DS9-s02e19.Blood.Oath_[reduced]_staxrip.txt](https://github.com/stax76/staxrip/files/997771/Star.Trek.DS9-s02e19.Blood.Oath_.reduced._staxrip.txt)

**Comment by stax76** [comment] 2017-05-12 20:15
The eac3to sections shows that eac3to writes the chapters entry to the m4a file.

Next build will have a workaround.

**Comment by Zcehtro** [comment] 2017-05-12 20:17
Ok. I'll test it when it's up.

**Comment by stax76** [comment] 2017-05-18 11:13
If it works we can close the issue.

**Comment by Zcehtro** [comment] 2017-05-18 11:20
Yes, it is working now. Thank you stax. Great job!

**Closed** 2017-05-18 11:20 UTC
